# Generated by Django 5.2.4 on 2026-02-09 17:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('fisherman', 'Fisherman'), ('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('delivery_location', models.CharField(max_length=200)),
                ('delivery_address', models.TextField(blank=True)),
                ('preferred_fulfillment', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='delivery', max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('delivery_notes', models.TextField(blank=True, help_text='Special delivery instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
        migrations.CreateModel(
            name='FishermanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_details', models.TextField(help_text='Additional contact information')),
                ('fulfillment_method', models.CharField(choices=[('pickup', 'Pickup Only'), ('delivery', 'Delivery Only'), ('both', 'Pickup and Delivery')], default='both', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the fisherman is verified')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_sales', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fisherman_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fisherman Profile',
                'verbose_name_plural': 'Fisherman Profiles',
            },
        ),
    ]
