# Generated by Django 4.2.27 on 2026-02-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_bio_user_phone_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishermanprofile',
            name='mpesa_account_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fishermanprofile',
            name='mpesa_paybill_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fishermanprofile',
            name='mpesa_payment_type',
            field=models.CharField(choices=[('STK_PUSH', 'STK Push'), ('TILL', 'Till'), ('PAYBILL', 'Paybill')], default='STK_PUSH', max_length=20),
        ),
        migrations.AddField(
            model_name='fishermanprofile',
            name='mpesa_phone',
            field=models.CharField(blank=True, help_text='M-Pesa phone in local or 254 format', max_length=20),
        ),
        migrations.AddField(
            model_name='fishermanprofile',
            name='mpesa_till_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('fisherman', 'Fisherman'), ('customer', 'Customer'), ('delivery', 'Delivery / Pickup'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
