# Generated by Django 5.2.4 on 2026-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role_beachchairmanprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('fisherman', 'Fisherman'), ('customer', 'Customer'), ('chairman', 'Beach Chairman'), ('delivery', 'Delivery Agent'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
