# Generated by Django 4.2.30 on 2026-07-29 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_fix_updated_at_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.DeleteModel(
            name='PhoneVerificationTransaction',
        ),
    ]
