# Generated by Django 5.2.4 on 2026-01-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_type', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('location', models.CharField(max_length=100)),
                ('catch_date', models.DateField()),
                ('status', models.CharField(choices=[('unsold', 'Unsold'), ('sold', 'Sold'), ('donated', 'Donated')], default='unsold', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catch',
                'verbose_name_plural': 'Catches',
                'ordering': ['-catch_date', '-created_at'],
            },
        ),
    ]
