# Generated by Django 5.2.4 on 2026-02-09 17:09

import django.db.models.deletion
import fishing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fish_type', models.CharField(choices=[('tilapia', 'Tilapia'), ('catfish', 'Catfish'), ('sardine', 'Sardine'), ('tuna', 'Tuna'), ('salmon', 'Salmon'), ('mackerel', 'Mackerel'), ('cod', 'Cod'), ('snapper', 'Snapper'), ('prawns', 'Prawns'), ('crab', 'Crab'), ('lobster', 'Lobster'), ('octopus', 'Octopus'), ('squid', 'Squid'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fish_images/')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_weight', models.DecimalField(decimal_places=2, help_text='Available weight in kg', max_digits=8)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('catch_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_organic', models.BooleanField(default=False, help_text='Wild-caught/organic fish')),
                ('is_frozen', models.BooleanField(default=False, help_text='Fish is frozen')),
                ('preparation_notes', models.TextField(blank=True, help_text='Cleaning, filleting instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fish Listing',
                'verbose_name_plural': 'Fish Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in kg', max_digits=8)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fishing.cart')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.fish')),
            ],
        ),
        migrations.CreateModel(
            name='FishTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LISTED', 'Fish Listed'), ('PURCHASED', 'Fish Purchased'), ('STOCK_ADJUSTED', 'Stock Adjusted'), ('STATUS_CHANGED', 'Status Changed'), ('DELETED', 'Fish Deleted')], max_length=20)),
                ('weight_change', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='fishing.fish')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=fishing.models.generate_order_number, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('READY', 'Ready for Fulfillment'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('PICKED_UP', 'Picked Up'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fulfillment_method', models.CharField(default='delivery', max_length=20)),
                ('delivery_location', models.CharField(blank=True, max_length=200)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready for Pickup/Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('PICKED_UP', 'Picked Up'), ('FAILED', 'Delivery Failed')], default='PENDING', max_length=20)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivery_person_name', models.CharField(blank=True, max_length=100)),
                ('delivery_person_phone', models.CharField(blank=True, max_length=20)),
                ('delivery_notes', models.TextField(blank=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='delivery_signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fisherman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='fishing.order')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=100)),
                ('fish_type', models.CharField(max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fulfillment_status', models.CharField(default='PENDING', max_length=20)),
                ('fish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='fishing.fish')),
                ('fisherman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_items', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fishing.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fishing.order')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
            },
        ),
        migrations.DeleteModel(
            name='Catch',
        ),
    ]
