# Generated by Django 4.2.27 on 2026-02-11 19:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fishing', '0003_cart_fish_cartitem_fishtransactionlog_order_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('general_location', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='fishermen_net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fisherman_net_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='fisherman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fisherman_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='net_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fishing.orderitem'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='unit_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('DELIVERY_IN_PROGRESS', 'Delivery In Progress'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='fishtransactionlog',
            name='action',
            field=models.CharField(choices=[('LISTED', 'Fish Listed'), ('PURCHASED', 'Fish Purchased'), ('RESERVED', 'Fish Reserved'), ('STOCK_RELEASED', 'Stock Released'), ('PAYMENT_RECEIVED', 'Payment Received'), ('STOCK_ADJUSTED', 'Stock Adjusted'), ('STATUS_CHANGED', 'Status Changed'), ('DELETED', 'Fish Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fishtransactionlog',
            name='fish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='fishing.fish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('FULLY_PAID', 'Fully Paid'), ('DELIVERY_IN_PROGRESS', 'Delivery In Progress'), ('PROCESSING', 'Processing'), ('READY', 'Ready for Fulfillment'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('PICKED_UP', 'Picked Up'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='fishing.delivery')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_audit_logs', to='fishing.order')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='fishing.pickuppoint'),
        ),
    ]
