# Generated by Django 4.2.27 on 2026-02-11 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fishing', '0004_pickuppoint_delivery_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_item', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_earnings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_notifications', to=settings.AUTH_USER_MODEL)),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_notifications', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_notifications', to='fishing.order')),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_notifications', to='fishing.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
