# Generated by Django 5.2.4 on 2026-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0009_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='fish',
            name='fish_type',
            field=models.CharField(choices=[('tilapia', 'Tilapia (Ngege)'), ('nile_perch', 'Nile Perch (Mbuta)'), ('catfish', 'African Catfish (Semu)'), ('omena', 'Dagaa / Omena'), ('lungfish', 'Lungfish (Kamongo)'), ('mudfish', 'Mudfish'), ('barbel', 'Barbel'), ('other', 'Other (Lake Victoria Species)')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('FULLY_PAID', 'Fully Paid'), ('DELIVERY_IN_PROGRESS', 'Delivery In Progress'), ('PROCESSING', 'Processing'), ('READY', 'Ready for Fulfillment'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('PICKED_UP', 'Picked Up'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=20),
        ),
    ]
