# Generated by Django 5.2.4 on 2026-03-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0010_alter_delivery_status_alter_fish_fish_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='b2c_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='b2c_conversation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='b2c_originator_conversation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='b2c_response_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='b2c_result_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='b2c_status',
            field=models.CharField(default='NOT_SENT', max_length=20),
        ),
    ]
