# Generated by Django 5.2.4 on 2026-03-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0011_paymenttransaction_b2c_attempted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='b2c_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
